from colorama import Fore,Back,Style

print(Back.BLACK + " "*100)
print(Back.BLACK + " "*20 + Fore.WHITE + "*" + " "*79)
print(Back.BLACK + " "*75 + Fore.WHITE + "*" + " "*24)
print(Back.BLACK + " "*35 + Fore.WHITE + "*" + " "*64)
print(Back.BLACK + " "*100)
print(Back.BLACK + " "*55 + Fore.WHITE + "*" + " "*44)
print(Back.BLACK + " "*10 + Fore.WHITE + "*" + " "*89)
print(Back.BLACK + " "*39 + Back.LIGHTBLUE_EX + " " + Back.BLACK + " "*39 + Fore.WHITE + "*" + " "*20)
print(Back.BLACK + " "*38 + Back.LIGHTBLUE_EX + " "*3 + Back.BLACK + " "*59)
print(Back.BLACK + " "*15 + Back.LIGHTBLUE_EX + " " + Back.BLACK + " "*21 + Back.LIGHTBLUE_EX + " "*5 + Back.BLACK + " "*58)
print(Back.BLACK + " "*14 + Back.LIGHTBLUE_EX + " "*3 + Back.BLACK + " "*21 + Back.BLUE + " "*3 + Back.BLACK + " "*59)
print(Back.BLACK + " "*13 + Back.LIGHTBLUE_EX + " "*5 + Back.BLACK + " "*8 + Back.LIGHTBLUE_EX + " " + Back.BLACK + " "*11 + Back.BLUE + " "*3 + Back.BLACK + " "*59)
print(Back.BLACK + " "*14 + Back.BLUE + " "*3 + Back.BLACK + " "*8 + Back.LIGHTBLUE_EX + " "*3 + Back.BLACK + " "*10 + Back.BLUE + " "*3 + Back.BLACK + " "*59)
print(Back.BLACK + " "*14 + Back.BLUE + " "*3 + Back.BLACK + " "*7 + Back.LIGHTBLUE_EX + " "*5 + Back.BLACK + " "*9 + Back.BLUE + " "*3 + Back.BLACK + " "*18 + Fore.WHITE + "*" + Back.BLACK + " "*40)
print(Back.BLACK + " "*14 + Back.BLUE + " "*3 + Back.BLACK + " "*6 + Back.LIGHTBLUE_EX + " "*7 + Back.BLACK + " "*8 + Back.BLUE + " "*3 + Back.BLACK + " "*59)
print(Back.BLACK + " "*14 + Back.BLUE + " "*3 + Back.BLACK + " "*5 + Back.LIGHTBLUE_EX + " "*9 + Back.BLACK + " "*7 + Back.BLUE + " "*3 + Back.BLACK + " "*59)
print(Back.BLACK + " "*14 + Back.BLUE + " "*3 + Back.BLACK + " "*4 + Back.LIGHTBLUE_EX + " "*11 + Back.BLACK + " "*6 + Back.BLUE + " "*3 + Back.BLACK + " "*59)
print(Back.BLACK + " "*14 + Back.BLUE + " "*3 + Back.BLACK + " "*3 + Back.LIGHTBLUE_EX + " "*13 + Back.BLACK + " "*5 + Back.BLUE + " "*3 + Back.BLACK + " "*59)
print(Back.BLACK + " "*14 + Back.BLUE + " "*3 + Back.BLACK + " "*2 + Back.LIGHTBLUE_EX + " "*15 + Back.BLACK + " "*4 + Back.BLUE + " "*3 + Back.BLACK + " "*28 + Fore.WHITE + "*" + Back.BLACK + " "*30)
print(Back.BLACK + " "*14 + Back.BLUE + " "*3 + Back.BLACK + " " + Back.LIGHTBLUE_EX + " "*17 + Back.BLACK + " "*3 + Back.BLUE + " "*3 + Back.BLACK + " "*59)
print(Back.BLACK + " "*14 + Back.BLUE + " "*3 + Back.LIGHTBLUE_EX + " "*19 + Back.BLACK + " "*2 + Back.BLUE + " "*3 + Back.BLACK + " "*59)
print(Back.BLACK + " "*14 + Back.BLUE + " "*2 + Back.LIGHTBLUE_EX + " "*21 + Back.BLACK + " " + Back.BLUE + " "*3 + Back.BLACK + " "*59)
print(Back.BLACK + " "*14 + Back.BLUE + " " + Back.LIGHTBLUE_EX + " "*23 + Back.BLUE + " "*3 + Back.BLACK + " "*59)
print(Back.BLACK + " "*14 + Back.LIGHTBLUE_EX + " "*25 + Back.BLUE + " "*2 + Back.BLACK + " "*59)
print(Back.BLACK + " "*13 + Back.LIGHTBLUE_EX + " "*27 + Back.BLUE + " " + Back.BLACK + " "*59)
print(Back.BLACK + " "*12 + Back.LIGHTBLUE_EX + " "*29+ Back.BLACK + " "*59)
print(Back.BLACK + " "*11 + Back.LIGHTBLUE_EX + " "*31+ Back.BLACK + " "*58)
print(Back.BLACK + " "*12 + Back.BLUE + " "*29 + Back.BLACK + " "*59)
print(Back.BLACK + " "*9 + Back.BLUE + " " + Back.BLACK + " "*2 + Back.BLUE + " "*14 + Back.GREEN + " "*4 + Back.BLUE + " "*3 + Back.YELLOW + " "*4 + Back.BLUE + " "*4 + Back.BLACK + " "*59)
print(Back.BLACK + " "*9 + Back.BLUE + " " + Back.BLACK + " "*2 + Back.BLUE + " "*11 + Back.LIGHTCYAN_EX + " " + Back.BLUE + " "*2 + Back.GREEN + " "*4 + Back.BLUE + " "*3 + Back.YELLOW + " "*4 + Back.BLUE + " "*4 + Back.BLACK + " "*60)
print(Back.BLACK + " "*9 + Back.BLUE + " " + Back.BLACK + " "*2 + Back.BLUE + " "*11 + Back.LIGHTCYAN_EX + " " + Back.BLUE + " "*2 + Back.GREEN + " "*4 + Back.BLUE + " "*11 + Back.BLACK + " "*60)
print(Back.BLACK + " "*9 + Back.BLUE + " "*3 + Back.BLUE + " "*11 + Back.LIGHTCYAN_EX + " "*14 + Back.BLUE + " "*4 + Back.BLACK + " "*60)
print(Back.BLACK + " "*12 + Back.BLUE + " "*29 + Back.BLACK + " "*59)
print(Back.BLACK + " "*12 + Back.BLUE + " "*29 + Back.BLACK + " "*59)
print(Back.BLACK + " "*12 + Back.BLUE + " "*11 + Back.GREEN + " "*8 + Back.BLUE + " "*10 + Back.BLACK + " "*59)
print(Back.BLACK + " "*12 + Back.BLUE + " "*11 + Back.GREEN + " "*8 + Back.BLUE + " "*10 + Back.BLACK + " "*7 + Back.RED + "  Sepehr     " + Back.BLACK + " "*39)
print(Back.BLACK + " "*12 + Back.BLUE + " "*11 + Back.GREEN + " "*8 + Back.BLUE + " "*10 + Back.BLACK + " "*7 + Back.RED + "  Mohammady  " + Back.BLACK + " "*39)
print(Back.BLACK + " "*12 + Back.BLUE + " "*11 + Back.GREEN + " "*8 + Back.BLUE + " "*10 + Back.BLACK + " "*9 + Back.RED + " "*2 + Back.BLACK + " "*5 + Back.RED + " "*2 + Back.BLACK + " "*41)
print(Back.BLACK + " "*12 + Back.BLUE + " "*11 + Back.GREEN + " "*8 + Back.BLUE + " "*10 + Back.BLACK + " "*9 + Back.RED + " "*2 + Back.BLACK + " "*5 + Back.RED + " "*2 + Back.BLACK + " "*41)
print(Back.BLACK + " "*100)
print(Back.BLACK + " "*10 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*14)
print(Back.BLACK + " "*10 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*14)
print(Back.RED + " "*99 + Back.BLACK + " ")
print(Back.RED + " "*99 + Back.BLACK + " ")
print(Back.BLACK + " "*10 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*14)
print(Back.BLACK + " "*10 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*15 + Back.RED + " "*4 + Back.BLACK + " "*14)
print(Back.BLACK + " "*100)

print(Style.RESET_ALL)
